const menu = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: './images/item-1.jpeg',
      desc: `A energy filled sweet breakfast of pancakes for the early riser.`,
    },
    {
      id: 2,
      title: 'cheese-cream bagel',
      category: 'breakfast',
      price: 13.99,
      img: './images/item-13.jpg',
      desc: `A donut designed sandwich bread that uses cream cheese for an early morning day`
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 6.99,
      img: './images/item-3.jpeg',
      desc: `A sweet drink containing cream and strawberries with donuts with a milk shake.`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: './images/item-4.jpeg',
      desc: `a plate of toast with sunnyside up eggs with some beans `,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: './images/item-5.jpeg',
      desc: `a giant burger with huge eggs with tomato, lettuce, and meat `,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: './images/item-6.jpeg',
      desc: `A milkshake created with oreos as the flavor for the milk.`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: './images/item-7.jpeg',
      desc: `a morning small sandwich using bisquits and some bacon and cheese for the morning`,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: './images/item-8.jpeg',
      desc: `a traditional burger with tomatos,cheese, and some french fries. `,
    },
    {
      id: 9,
      title: 'fudge ice cream',
      category: 'dessert',
      price: 16.99,
      img: './images/item-15.jpg',
      desc: `A lovely dessert of a chocolate deep fudge frozen to a perfect sweet sugary sweet.`,
    },
    {
      id: 10,
      title: 'Chocolate ice Cream',
      category: 'dessert',
      price: 16.99,
      img: './images/item-12.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 11,
      title: 'Pizza',
      category: 'lunch',
      price: 16.99,
      img: './images/item-14.jpg',
      desc: `A triangle slice of pie that uses tomato and cheese above a thin crust.`,
    },
    {
      id: 12,
      title: 'water',
      category: 'drinks',
      price: 0.00,
      img: './images/item-16.jpg',
      desc: `A common liquid found in most households.`,
    },
    {
      id: 13,
      title: 'pepsi',
      category: 'drinks',
      price: 2.99,
      img: './images/item-17.jpg',
      desc: `A sugar sweet drink that goes well with most lunches or dinners.`,
    },
    {
      id: 14,
      title: 'coke',
      category: 'drinks',
      price: 2.99,
      img: './images/item-18.jpg',
      desc: `A sugar sweet drink that goes well with most lunches or dinners.`,
    },
  ];
  export default menu